version: '3.9.7'
services:
  rpyc_metrics_server:
    build: rpyc_server/
    image: oneonwar/rpyc_metrics_server:0.0.7.8
    ulimits:
      nproc: 1024
      nofile:
        soft: 257426
        hard: 257426
    env_file:
      - .env
    container_name: rpyc_server
    ports:
      - "18861:18861"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "18861"]
      interval: 1m
      retries: 30
    networks:
      - network


  idu_metrics:
    build: metrics/
    image: oneonwar/idu_metrics:2.5.3.8
    ulimits:
      nproc: 1024
      nofile:
        soft: 257426
        hard: 257426
    container_name: metrics
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      rpyc_metrics_server:
        condition: service_healthy
    ports:
      - "5000:5000"
    networks:
      - network
    volumes:
      - ./metrics/app:/app/app
      - ./metrics/calculations:/app/calculations


networks:
  network:
    driver: bridge